// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9ZGBJqaf6u9z_Xhrol-k6Tou4RYl89U',
    appId: '1:137688050211:android:52eab106e972150754df96',
    messagingSenderId: '137688050211',
    projectId: 'app-demo-with-apsl-ads',
    databaseURL: 'https://app-demo-with-apsl-ads-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-demo-with-apsl-ads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUNdQLAKhzUDoVg5JaihK_9BLHdgHrBxE',
    appId: '1:137688050211:ios:3daf082041c72ffb54df96',
    messagingSenderId: '137688050211',
    projectId: 'app-demo-with-apsl-ads',
    databaseURL: 'https://app-demo-with-apsl-ads-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-demo-with-apsl-ads.appspot.com',
    iosClientId: '137688050211-sclp7itrp432mp4nrkde7869nflj0irh.apps.googleusercontent.com',
    iosBundleId: 'com.appstonelab.apsladsdemo',
  );
}
